### ISSUE TITLE
How to add section of Firefox Hello into contacts

### ISSUE THREAD

**Issue by airon90** [mozilla-b2g/firefoxos-loop-client#449]
Hello, I know that it is just a question and not a bug so I'm sorry if I'm using uncorrectly the bug tracker.
I installed Firefox Hello on my Flame and I saw that in every contact there is a section named "Firefox Hello" and two buttons, "Audio" and "Video".
Where can I find in the docs how to add such buttons in the contact and where can I find the code on firefoxos-loop-client about this feature?
Thank you very much!

**Comment by oteo** [comment]
The integration is achieved via an activity exposed by Hello application, "webrtc-call", it is used by the Gaia Contacts app to trigger a Firefox Hello call from the contact view. This activity takes a MozContacts object as a parameter and it is opened in a new window.

Hello activities are implemented here: https://github.com/mozilla-b2g/firefoxos-loop-client/blob/master/app/js/helpers/activities.js

The code in which activities are used from contacts is here: https://github.com/mozilla-b2g/gaia/blob/master/apps/communications/contacts/js/webrtc-client/webrtc_client.js
