### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by aronnebrivio** [mozilla-b2g/firefoxos-loop-client#484]
Audio is not working while calling someone using Firefox OS client. All ok from a pc, so the client send both audio and video, but receives only video

**Comment by oteo** [comment]
We have not reproduced that bug :(.
If you have a specific STR that can help us to address that issue, please open a bug in https://bugzilla.mozilla.org, setting
Product:Firefox OS
Component: Gaia::Loop
Thanks a lot for your feedback!

**Comment by aroblu94** [comment]
I think probably it's not the correct place to talk about it but... Is there a way to have a logcat in order to "document" the bug's affecting me?
Anyway it could be related to Firefox OS 3.0 prereleasr I'm runming on my device
