### ISSUE TITLE
Firefox hello is not working in flame device

### ISSUE THREAD

**Issue by amjadm61** [mozilla-b2g/firefoxos-loop-client#569]
I can install this app successfully in my flame device. But while trying to run this app, they are saying "your device is not compatible with this app".

**Comment by crdlc** [comment]
Please take a look at your user-agent because you should be able to see what your user agent contains 'ALCATELOneTouch6015X' or 'Mozilla'

https://github.com/mozilla-b2g/firefoxos-loop-client/blob/master/app/compatibility.json

**Comment by amjadm61** [comment]
@crdlc, Can you plz make it more clear? I'm using Flame reference device with fxOS 2.0. Can I install fx hello? If So, How?

**Comment by crdlc** [comment]
AFAIR all the info is available in de README

https://github.com/mozilla-b2g/firefoxos-loop-client/blob/master/README.md

**Comment by schonjones** [comment]
I had no problems pulling it from here and running it on My flame running 3.0 nightly. if you allow the install from a hello chat link however this error message does occur.

**Comment by amjadm61** [comment]
Yes, The error occured while I'm trying to install hello from the chat link.
I installed hello by pulling it from here. Its now working fine.
Thanks all :)
