### ISSUE TITLE
Couldn't sign in by using my flame 3.0 nightly

### ISSUE THREAD

**Issue by amjadm61** [mozilla-b2g/firefoxos-loop-client#576]
![index](https://cloud.githubusercontent.com/assets/4783625/7761867/35808260-0049-11e5-8e67-7ce02a2cc64d.png)

I just pushed the firefox hello app into my flame (running 3.0 nightly). I tried with both firefox account and phone number for sign in into the Hello. But It showing like in the screenshot that I attached here.
I waited there actually for 20 minutes, But no positive result.... :(

**Comment by ibotty** [comment]
Also happens on my nexus 4 (-kk) running nightly from today.

**Comment by kamil7x** [comment]
I don't know if this is same issue, but I can't authenticate on Flame (running 2.5 nightly). I tried both Firefox Account and phone number (i am logged in to Firefox Account in my phone)

![screen](https://cloud.githubusercontent.com/assets/7629808/8504122/78c1838c-21cb-11e5-9956-48a14204a473.png)

**Comment by SamuelMoraesF** [comment]
+1

I'm having issues with autentication over Firefox Accounts and with my phone number(the same errors above)

**Comment by gmarty** [comment]
I can confirm this issue on a Sony Z3C flashed with the latest master.
Same problem as the screenshot above ('Sorry, the logging process failed...').
